import { initContract } from '@ts-rest/core';
import { z } from 'zod';
import { ApiResponseSchema } from '../base';
import {
  CreateStudioProjectSchema,
  PreviewStudioProjectImportSchema,
  StudioProjectImportPreviewSchema,
  ConfirmStudioProjectImportSchema,
  StudioProjectImportResultSchema,
  CreateStudioAdaptationSchema,
  StudioAdaptationProjectSchema,
  StudioAdaptationListQuerySchema,
  StudioAdaptationListResponseSchema,
  CreateStudioChapterDraftSchema,
  CreateStudioAuthorRevisionSchema,
  GenerationJobSchema,
  StudioBlueprintSchema,
  StudioBlueprintListQuerySchema,
  StudioBlueprintListResponseSchema,
  StudioChapterPlanSchema,
  StudioChapterRevisionSchema,
  StudioChapterRevisionListQuerySchema,
  StudioChapterRevisionListResponseSchema,
  StudioChapterRevisionDiffSchema,
  StudioBlueprintRestoreResultSchema,
  StudioChapterFinalRestoreResultSchema,
  StudioChapterFinalizationSchema,
  StudioChapterFinalizationListQuerySchema,
  StudioChapterFinalizationListResponseSchema,
  CreateStudioFactChangeSchema,
  ResolveStudioFactChangeSchema,
  StudioFactChangeListQuerySchema,
  StudioFactChangeListResponseSchema,
  StudioFactChangeSchema,
  StudioFactListQuerySchema,
  StudioFactListResponseSchema,
  StudioReviewFindingListQuerySchema,
  StudioReviewFindingListResponseSchema,
  StudioReviewFindingSchema,
  ResolveStudioReviewFindingSchema,
  StudioProjectListQuerySchema,
  StudioProjectListResponseSchema,
  StudioProjectExportQuerySchema,
  StudioProjectExportSchema,
  StudioProjectOverviewSchema,
  StudioProjectEventListQuerySchema,
  StudioProjectEventListResponseSchema,
  StudioFinalizationTaskListQuerySchema,
  StudioFinalizationTaskListResponseSchema,
  StudioFinalizationTaskSchema,
  UpdateStudioChapterPlanSchema,
  UpdateStudioBlueprintSchema,
} from '../schemas/studio.schema';

const c = initContract();

export const studioContract = c.router(
  {
    listProjects: {
      method: 'GET',
      path: '/projects',
      query: StudioProjectListQuerySchema,
      responses: {
        200: ApiResponseSchema(StudioProjectListResponseSchema),
      },
      summary: 'List the current author writing projects',
    },
    previewProjectImport: {
      method: 'POST',
      path: '/imports/preview',
      body: PreviewStudioProjectImportSchema,
      responses: { 201: ApiResponseSchema(StudioProjectImportPreviewSchema) },
      summary: 'Store original source bytes and return a chapter import preview',
    },
    confirmProjectImport: {
      method: 'POST',
      path: '/imports/:importId/confirm',
      pathParams: z.object({ importId: z.string().uuid() }),
      body: ConfirmStudioProjectImportSchema,
      responses: { 201: ApiResponseSchema(StudioProjectImportResultSchema) },
      summary: 'Create a project from a reviewed legacy manuscript import',
    },
    listAdaptations: {
      method: 'GET',
      path: '/projects/:projectId/adaptations',
      pathParams: z.object({ projectId: z.string().uuid() }),
      query: StudioAdaptationListQuerySchema,
      responses: { 200: ApiResponseSchema(StudioAdaptationListResponseSchema) },
      summary: 'List screenplay adaptations created from a source novel',
    },
    createAdaptation: {
      method: 'POST',
      path: '/projects/:projectId/adaptations',
      pathParams: z.object({ projectId: z.string().uuid() }),
      body: CreateStudioAdaptationSchema,
      responses: { 201: ApiResponseSchema(StudioAdaptationProjectSchema) },
      summary: 'Create an adaptation from immutable finalized novel chapters',
    },
    exportProject: {
      method: 'GET',
      path: '/projects/:projectId/export',
      pathParams: z.object({ projectId: z.string().uuid() }),
      query: StudioProjectExportQuerySchema,
      responses: { 200: ApiResponseSchema(StudioProjectExportSchema) },
      summary: 'Export current finalized chapters with metadata and review warnings',
    },
    getProjectOverview: {
      method: 'GET',
      path: '/projects/:projectId/overview',
      pathParams: z.object({ projectId: z.string().uuid() }),
      responses: { 200: ApiResponseSchema(StudioProjectOverviewSchema) },
      summary: 'Get finalized progress, facts, review findings, and background task counts',
    },
    listProjectEvents: {
      method: 'GET',
      path: '/projects/:projectId/events',
      pathParams: z.object({ projectId: z.string().uuid() }),
      query: StudioProjectEventListQuerySchema,
      responses: { 200: ApiResponseSchema(StudioProjectEventListResponseSchema) },
      summary: 'Replay durable generation and finalization task events for a project',
    },
    listFinalizationTasks: {
      method: 'GET',
      path: '/projects/:projectId/finalization-tasks',
      pathParams: z.object({ projectId: z.string().uuid() }),
      query: StudioFinalizationTaskListQuerySchema,
      responses: { 200: ApiResponseSchema(StudioFinalizationTaskListResponseSchema) },
      summary: 'List durable summary and index outbox tasks for a project',
    },
    retryFinalizationTask: {
      method: 'POST',
      path: '/projects/:projectId/finalization-tasks/:taskId/retry',
      pathParams: z.object({ projectId: z.string().uuid(), taskId: z.string().uuid() }),
      body: z.object({}),
      responses: { 200: ApiResponseSchema(StudioFinalizationTaskSchema) },
      summary: 'Retry a failed or recoverable finalization outbox task',
    },
    createProject: {
      method: 'POST',
      path: '/projects',
      body: CreateStudioProjectSchema,
      responses: {
        202: ApiResponseSchema(GenerationJobSchema),
      },
      summary: 'Create a writing project and start its generation job',
    },
    getBlueprint: {
      method: 'GET',
      path: '/projects/:projectId/blueprint',
      pathParams: z.object({ projectId: z.string().uuid() }),
      responses: {
        200: ApiResponseSchema(StudioBlueprintSchema),
      },
      summary: 'Get the latest editable blueprint for the current author project',
    },
    listBlueprints: {
      method: 'GET',
      path: '/projects/:projectId/blueprints',
      pathParams: z.object({ projectId: z.string().uuid() }),
      query: StudioBlueprintListQuerySchema,
      responses: { 200: ApiResponseSchema(StudioBlueprintListResponseSchema) },
      summary: 'List versioned blueprints available for safe restore',
    },
    updateBlueprint: {
      method: 'PUT',
      path: '/projects/:projectId/blueprint',
      pathParams: z.object({ projectId: z.string().uuid() }),
      body: UpdateStudioBlueprintSchema,
      responses: {
        200: ApiResponseSchema(StudioBlueprintSchema),
      },
      summary: 'Save an editable project blueprint',
    },
    confirmBlueprint: {
      method: 'POST',
      path: '/projects/:projectId/blueprint/confirm',
      pathParams: z.object({ projectId: z.string().uuid() }),
      body: z.object({}),
      responses: {
        200: ApiResponseSchema(StudioBlueprintSchema),
      },
      summary: 'Confirm the latest project blueprint',
    },
    restoreBlueprint: {
      method: 'POST',
      path: '/projects/:projectId/blueprints/:blueprintId/restore',
      pathParams: z.object({
        projectId: z.string().uuid(),
        blueprintId: z.string().uuid(),
      }),
      body: z.object({}),
      responses: {
        200: ApiResponseSchema(StudioBlueprintRestoreResultSchema),
      },
      summary: 'Restore a confirmed historical blueprint and report affected chapter plans',
    },
    getChapterPlan: {
      method: 'GET',
      path: '/projects/:projectId/chapters/:chapterNumber/plan',
      pathParams: z.object({
        projectId: z.string().uuid(),
        chapterNumber: z.coerce.number().int().positive(),
      }),
      responses: {
        200: ApiResponseSchema(StudioChapterPlanSchema),
      },
      summary: 'Get the latest chapter plan for the current author project',
    },
    saveChapterPlan: {
      method: 'PUT',
      path: '/projects/:projectId/chapters/:chapterNumber/plan',
      pathParams: z.object({
        projectId: z.string().uuid(),
        chapterNumber: z.coerce.number().int().positive(),
      }),
      body: UpdateStudioChapterPlanSchema,
      responses: {
        200: ApiResponseSchema(StudioChapterPlanSchema),
      },
      summary: 'Save a structured chapter plan from the confirmed blueprint',
    },
    confirmChapterPlan: {
      method: 'POST',
      path: '/projects/:projectId/chapters/:chapterNumber/plan/confirm',
      pathParams: z.object({
        projectId: z.string().uuid(),
        chapterNumber: z.coerce.number().int().positive(),
      }),
      body: z.object({}),
      responses: {
        200: ApiResponseSchema(StudioChapterPlanSchema),
      },
      summary: 'Confirm the current chapter plan before drafting',
    },
    createChapterDraft: {
      method: 'POST',
      path: '/projects/:projectId/chapters/:chapterNumber/drafts',
      pathParams: z.object({
        projectId: z.string().uuid(),
        chapterNumber: z.coerce.number().int().positive(),
      }),
      body: CreateStudioChapterDraftSchema,
      responses: {
        202: ApiResponseSchema(GenerationJobSchema),
      },
      summary: 'Generate an immutable draft from a confirmed chapter plan',
    },
    getChapterRevision: {
      method: 'GET',
      path: '/projects/:projectId/chapters/:chapterNumber/revisions/:revisionId',
      pathParams: z.object({
        projectId: z.string().uuid(),
        chapterNumber: z.coerce.number().int().positive(),
        revisionId: z.string().uuid(),
      }),
      responses: {
        200: ApiResponseSchema(StudioChapterRevisionSchema),
      },
      summary: 'Get an immutable chapter draft revision',
    },
    listChapterRevisions: {
      method: 'GET',
      path: '/projects/:projectId/chapters/:chapterNumber/revisions',
      pathParams: z.object({
        projectId: z.string().uuid(),
        chapterNumber: z.coerce.number().int().positive(),
      }),
      query: StudioChapterRevisionListQuerySchema,
      responses: {
        200: ApiResponseSchema(StudioChapterRevisionListResponseSchema),
      },
      summary: 'List immutable draft revisions and the current draft pointer',
    },
    restoreChapterRevision: {
      method: 'POST',
      path: '/projects/:projectId/chapters/:chapterNumber/revisions/:revisionId/restore',
      pathParams: z.object({
        projectId: z.string().uuid(),
        chapterNumber: z.coerce.number().int().positive(),
        revisionId: z.string().uuid(),
      }),
      body: z.object({}),
      responses: {
        200: ApiResponseSchema(StudioChapterRevisionSchema),
      },
      summary: 'Set an immutable draft revision as the current chapter draft',
    },
    restoreFinalChapterRevision: {
      method: 'POST',
      path: '/projects/:projectId/chapters/:chapterNumber/revisions/:revisionId/restore-final',
      pathParams: z.object({
        projectId: z.string().uuid(),
        chapterNumber: z.coerce.number().int().positive(),
        revisionId: z.string().uuid(),
      }),
      body: z.object({}),
      responses: {
        200: ApiResponseSchema(StudioChapterFinalRestoreResultSchema),
      },
      summary: 'Restore a historical finalized revision and its fact snapshot',
    },
    listChapterFinalizations: {
      method: 'GET',
      path: '/projects/:projectId/chapters/:chapterNumber/finalizations',
      pathParams: z.object({
        projectId: z.string().uuid(),
        chapterNumber: z.coerce.number().int().positive(),
      }),
      query: StudioChapterFinalizationListQuerySchema,
      responses: { 200: ApiResponseSchema(StudioChapterFinalizationListResponseSchema) },
      summary: 'List finalized chapter history available for restore',
    },
    createAuthorChapterRevision: {
      method: 'POST',
      path: '/projects/:projectId/chapters/:chapterNumber/revisions/:revisionId/author-revisions',
      pathParams: z.object({
        projectId: z.string().uuid(),
        chapterNumber: z.coerce.number().int().positive(),
        revisionId: z.string().uuid(),
      }),
      body: CreateStudioAuthorRevisionSchema,
      responses: { 201: ApiResponseSchema(StudioChapterRevisionSchema) },
      summary: 'Create an immutable author revision from the current chapter draft',
    },
    finalizeChapterRevision: {
      method: 'POST',
      path: '/projects/:projectId/chapters/:chapterNumber/revisions/:revisionId/finalize',
      pathParams: z.object({
        projectId: z.string().uuid(),
        chapterNumber: z.coerce.number().int().positive(),
        revisionId: z.string().uuid(),
      }),
      body: z.object({}),
      responses: { 201: ApiResponseSchema(StudioChapterFinalizationSchema) },
      summary: 'Finalize the current draft after all fact changes are resolved',
    },
    compareChapterRevisions: {
      method: 'GET',
      path: '/projects/:projectId/chapters/:chapterNumber/revisions/:revisionId/compare/:comparisonRevisionId',
      pathParams: z.object({
        projectId: z.string().uuid(),
        chapterNumber: z.coerce.number().int().positive(),
        revisionId: z.string().uuid(),
        comparisonRevisionId: z.string().uuid(),
      }),
      responses: {
        200: ApiResponseSchema(StudioChapterRevisionDiffSchema),
      },
      summary: 'Compare two immutable chapter draft revisions',
    },
    listFacts: {
      method: 'GET',
      path: '/projects/:projectId/facts',
      pathParams: z.object({ projectId: z.string().uuid() }),
      query: StudioFactListQuerySchema,
      responses: { 200: ApiResponseSchema(StudioFactListResponseSchema) },
      summary: 'List confirmed project facts available as change targets',
    },
    listFactChanges: {
      method: 'GET',
      path: '/projects/:projectId/chapters/:chapterNumber/revisions/:revisionId/fact-changes',
      pathParams: z.object({
        projectId: z.string().uuid(),
        chapterNumber: z.coerce.number().int().positive(),
        revisionId: z.string().uuid(),
      }),
      query: StudioFactChangeListQuerySchema,
      responses: { 200: ApiResponseSchema(StudioFactChangeListResponseSchema) },
      summary: 'List pending and resolved fact changes for a chapter draft',
    },
    createFactChange: {
      method: 'POST',
      path: '/projects/:projectId/chapters/:chapterNumber/revisions/:revisionId/fact-changes',
      pathParams: z.object({
        projectId: z.string().uuid(),
        chapterNumber: z.coerce.number().int().positive(),
        revisionId: z.string().uuid(),
      }),
      body: CreateStudioFactChangeSchema,
      responses: { 201: ApiResponseSchema(StudioFactChangeSchema) },
      summary: 'Create a fact change proposal for a chapter draft',
    },
    resolveFactChange: {
      method: 'POST',
      path: '/projects/:projectId/chapters/:chapterNumber/revisions/:revisionId/fact-changes/:changeId/decision',
      pathParams: z.object({
        projectId: z.string().uuid(),
        chapterNumber: z.coerce.number().int().positive(),
        revisionId: z.string().uuid(),
        changeId: z.string().uuid(),
      }),
      body: ResolveStudioFactChangeSchema,
      responses: { 200: ApiResponseSchema(StudioFactChangeSchema) },
      summary: 'Accept, edit, or reject a proposed fact change',
    },
    listReviewFindings: {
      method: 'GET',
      path: '/projects/:projectId/chapters/:chapterNumber/revisions/:revisionId/review-findings',
      pathParams: z.object({
        projectId: z.string().uuid(),
        chapterNumber: z.coerce.number().int().positive(),
        revisionId: z.string().uuid(),
      }),
      query: StudioReviewFindingListQuerySchema,
      responses: { 200: ApiResponseSchema(StudioReviewFindingListResponseSchema) },
      summary: 'List persistent review findings for a chapter revision',
    },
    resolveReviewFinding: {
      method: 'POST',
      path: '/projects/:projectId/chapters/:chapterNumber/revisions/:revisionId/review-findings/:findingId/decision',
      pathParams: z.object({
        projectId: z.string().uuid(),
        chapterNumber: z.coerce.number().int().positive(),
        revisionId: z.string().uuid(),
        findingId: z.string().uuid(),
      }),
      body: ResolveStudioReviewFindingSchema,
      responses: { 200: ApiResponseSchema(StudioReviewFindingSchema) },
      summary: 'Resolve, ignore, or record an intentional hard-fact change',
    },
    getJob: {
      method: 'GET',
      path: '/jobs/:jobId',
      pathParams: z.object({ jobId: z.string().uuid() }),
      responses: {
        200: ApiResponseSchema(GenerationJobSchema),
      },
      summary: 'Get the current generation job state',
    },
    retryJob: {
      method: 'POST',
      path: '/jobs/:jobId/retry',
      pathParams: z.object({ jobId: z.string().uuid() }),
      body: z.object({}),
      responses: {
        202: ApiResponseSchema(GenerationJobSchema),
      },
      summary: 'Retry a failed or interrupted generation job from its durable checkpoint',
    },
    cancelJob: {
      method: 'POST',
      path: '/jobs/:jobId/cancel',
      pathParams: z.object({ jobId: z.string().uuid() }),
      body: z.object({}),
      responses: { 202: ApiResponseSchema(GenerationJobSchema) },
      summary: 'Persist cancellation for a queued or running generation job',
    },
  },
  { pathPrefix: '/studio' },
);
